#! /bin/bash
for file in $( ls test | grep -E '^.*\.lua$')
do
    luac53 -o "test/"${file}"c" "test/"$file
    echo "Running "$file"..."
    lua53 ylua.lua "test/"$file"c"
    echo "----------------------------------"
done

